### ISSUE TITLE
Use alternate brewer palette when number of factors > 8

### ISSUE THREAD

**Issue by khughitt** [elsayed-lab/hpgltools#37]
Currently, a few of the plotting functions are hard-coded to use the `Dark2` palette. This occasionally results in warnings when there are more than eight factors, e.g.:

```
Warning message:
In RColorBrewer::brewer.pal(ncol(data), "Dark2") :
  n too large, allowed maximum for palette Dark2 is 8
Returning the palette you asked for with that many colors
```

**Comment by abelew** [comment]
nice catch.  I abused ... arguments to make that changeable with 
bob(palette="something"), it defaults to "Dark"  sending up a PR now.

**Comment by abelew** [comment]
crap it was supposed to be 'Dark2'

**Comment by abelew** [comment]
hmm crapples, there is a PR open and I am too stupid to figure out how to add a new one -- actually no github is just too smart and automagically did it -- that is kind of wonderful and obnoxious.

**Comment by khughitt** [comment]
:)

As long as you are working on the same branch (e.g. "master"), new commits
will get added to a PR.

**Comment by abelew** [comment]
fixed and defaulting all plots to dark2 palette.
