### ISSUE TITLE
build fails due to namespace error in bioconductor 3.3

### ISSUE THREAD

**Issue by khughitt** [elsayed-lab/hpgltools#45]
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) : 
  undefined exports: plot_gvis_ma, plot_gvis_scatter, plot_gvis_volcano
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/keith/R/x86_64-pc-linux-gnu-library/3.3/hpgltools’
Error: Command failed (1)

**Comment by abelew** [comment]
This should no longer be a problem, the namespace file wasn't being properly watched in git and would require one to do 'make roxygen'
